### ISSUE TITLE
Minimal info needed in depth file

### ISSUE THREAD

**Issue by aimirza** [xiaoli-dong/metaerg#16]
What is the minimal info and structure required in the coverage file (for the --depth input)? For some reason, jgi_summarize_bam_contig_depths outputs nothing on my bam files. Thus, I would like to create a coverage file using a different method.

**Comment by Finesim97** [comment]
MetaErg expects the column as named and output by `jgi_summarize_bam_contig_depths`.

The parser code is here:
https://github.com/xiaoli-dong/metaerg/blob/9fa2a57597f6882237bbcec1119844c3b26744e9/bin/metaerg.pl#L660

An example file is here:
https://github.com/xiaoli-dong/metaerg/blob/master/example/demo.depth.txt

It looks for the header `contigName` in the first column and then starts looking at the fourth column (jumping over contigName, contigLen, totalAvgDepth) ignoring column names ending with `-var` and removing the `.bam`or `_sorted.bam` from other column names, using the remainder then as the sample name.  totalAvgDepth is expected to be in the third position and contigName in the first.

A little bit odd, that `jgi_summarize_bam_contig_depths` outputs nothing. Have you sorted and indexed your BAM file? You could test running BBMap with the script/same parameters used in the MetaBAT2 paper just for comparison:
https://bitbucket.org/berkeleylab/metabat/src/master/MetaBAT2PaperSupplementaryScripts/runBBmap.sh

**Comment by Finesim97** [comment]
If `pileup.sh` works for you and you only have a single BAM file:
```
#ID	Avg_fold	Length	Ref_GC	Covered_percent	Covered_bases	Plus_reads	Minus_reads	Read_GC	Median_fold	Std_Dev
k127_14666	1.0000	301	0.0000	100.0000	301	1	0	0.4751	1	0.06
k127_29332	1.0000	301	0.0000	100.0000	301	1	0	0.4186	1	0.06
k127_197971	1.0000	301	0.0000	100.0000	301	0	1	0.3887	1	0.06
k127_87991	1.0000	301	0.0000	100.0000	301	0	1	0.4850	1	0.06
```
You could use AWK to reformat that file.
``` sh
awk -F'\t' -v OFS='\t' '{ if (NR==1) print "contigName","contigLen","totalAvgDepth","A.bam","A.bam-var"; else print $1,$3,$2,$2,$11;}' filehere
```
Output:
```
contigName	contigLen	totalAvgDepth	A.bam	A.bam-var
k127_14666	301	1.0000	1.0000	0.06
k127_29332	301	1.0000	1.0000	0.06
k127_197971	301	1.0000	1.0000	0.06
k127_87991	301	1.0000	1.0000	0.06
```
For more runs/bam files you probably should use a R/Python script.

**Comment by aimirza** [comment]
This is great info. I pipeline I'm using (Sunbeam) used MiniMap2 and samtools to create the single bam file. For some reason, it doesn't work on either `jgi_summarize_bam_contig_depths` or `pileup.sh` but the sunbeam coverage [script ](https://github.com/sunbeam-labs/sunbeam/blob/dev/rules/assembly/coverage.rules) was able to parse through the bam file to calculate coverage stats. I'll just have to reformat my coverage file into the format you described above. Thank you!

**Comment by aimirza** [comment]
Sorry, for some reason that sample I was testing, the smallest sample, did not assemble... The problem was that there were no assembled contigs... Anyways, this thread was helpful.
