### ISSUE TITLE
No content in output html reports?

### ISSUE THREAD

**Issue by Anto007** [xiaoli-dong/metaerg#17]
Hi, I followed the instructions on https://github.com/Finesim97/MetaErgInstallHelper to get metaerg on my PC. While the run gets completed without any issues, the 'html' subdirectory in the the main output directory has empty content within it? I mean that the files are written but there are only headers and footers to it with no actual results appearing. In contrast, the 'data' subdirectory has not only got all the files written but has also got content within each of them. For example, sequences are actually present on *.ffn, *.faa etc. files. I would appreciate any inputs on what may be going on here. The command-line I used after activating the conda environment is this:
(/home/XXX/metaerginstall) XXX@XXX: /data/metaerg_test$: meaterg.pl /data/metaerg_test/ERR3230147_metagenome.fasta --dbdir /data/metaerg_db/db --outdir /data/metaerg_test/ERR3230147_metagenome_output

**Comment by Finesim97** [comment]
Hi,
Do the last lines of the run log contain anything that seems out of place? From your command I guess your using this metagenome sample? https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=ERR3230147
Would you mind sharing your /data/metaerg_test/ERR3230147_metagenome.fasta ? Just so that I can try to reproduce the problem. If this is not possible, I will run my own metagenome pipeline on it.

**Comment by Anto007** [comment]
Many thanks Lukas for your super-quick response. The assembly file is too big to be attached here. Can you send me your mail id so that I can share with you the assembly and my metaerg output directory? I'm sorry I don't know where exactly to find the run log file? Can you please let me know? Thanks again!

**Comment by Finesim97** [comment]
Hi again,
The output is only produced during the actual run. For future runs redirect the output to a file:
``` sh
commandhere 2>&1 | tee run.log
```
Could you send your files to this address: throwaway-001 <> lukas-jansen.de
Also I need the output from `git log --oneline` run in the directory `/home/XXX/metaerginstall/metaerg`

**Comment by Anto007** [comment]
Thanks again; I've now emailed you all the files.

**Comment by Finesim97** [comment]
Really sry for the long wait.
I checked the files you've sent me. All files have tables/interactive elements in them. The files for abundance (`.abd.html`) sunbursts are empty, because you didn't provide a abundance file. If there is no abundance data, it maybe shouldn't generate and link them, this might be useful and not so weird. If I disable JavaScript in my Browser, I can only see the header+footer in all data files, could you try a different browser/computer/enable JavaScript?
Hope this helps,
Lukas Jansen

**Comment by Anto007** [comment]
Thank you for your kind response Lukas. I'm sorry I didn't understand what you wrote. Javascript is enabled on my multiple browsers and yet I see only header+footer. Anyways, there's no actual output data apart from the header & footer lines in the actual html output files (i.e., if I open them on terminal/text editor and see what's inside). Can you let me know what you mean by when you say I didn't provide an abundance file? I ran this command-line (/home/XXX/metaerginstall) XXX@XXX: /data/metaerg_test$: meaterg.pl /data/metaerg_test/ERR3230147_metagenome.fasta --dbdir /data/metaerg_db/db --outdir /data/metaerg_test/ERR3230147_metagenome_output. Now do you mean that I need to run an additional command-line to get the html outputs? If so, what is it? Thanks again for your time and support.

**Comment by Finesim97** [comment]
No problem.  Working example:
![Screenshot from 2020-03-05 13-08-48](https://user-images.githubusercontent.com/1181653/75980351-972ab600-5ee2-11ea-92f2-f322523ed46a.png)



The HTML files are only skeletons, the data is loaded from the data files (Based on a relative path(../data/xxxx)). But you are opening the HTML files within the output/html directory, while still having the remaining output directory around it, right?
Would you agree with this list:
```
html/
├── crisprTable.html # Working
├── kegg_minpath_summary.html # Working
├── kegg_minpath_summary.plevel.html # Empty, uses abundance data
├── metabolic_sunburst.abd.html # Empty, uses abundance data
├── metabolic_sunburst.count.html # Empty, broken?, but also not linked in the index.html
├── metabolictree_cds.html # Empty, broken?, but also not linked in the index.html
├── metacyc_minpath_summary.html # Working
├── protein_family_ec.html # Working
├── protein_family_go.html # Working
├── protein_family_ko.html # Working
├── protein_family_metabolic.html # Working
├── protein_family_metabolic_sunburst_abd.html # Empty, uses abundance data
├── protein_family_metabolic_sunburst_count.html # Working
├── protein_family_metabolic_tree.html # Working
├── protein_family_pfam.html # Working
├── protein_family_tigrfam.htm l# Working
├── rRNATable.html l# Working
├── sequences.js # Exists
├── sequences_taxon.js # Exists
├── style.tree.css # Exists
├── taxon_sunburst_cds.abd.html # Empty, uses abundance data
├── taxon_sunburst_cds.count.html # Working
├── taxon_sunburst_lsurRNA.abd.html  # Empty, uses abundance data
├── taxon_sunburst_lsurRNA.count.html # Working
├── taxon_sunburst_ssurRNA.abd.html # Empty, uses abundance data
├── taxon_sunburst_ssurRNA.count.html # Working
├── taxontable_cds.html # Working
├── taxontable_lsurRNA.html # Working
├── taxontable_ssurRNA.html # Working
├── taxontree_cds.html # Working
├── taxontree_lsurRNA.html # Working
├── taxontree_ssurRNA.html # Working
└── tRNATable.html # Working
```
Could you post a screenshot of the JavaScript Console for one of the for me working files.

Abundance data can be generated by mapping a read sample (for example that one used to generate the assembly) to the assembly.

**Comment by Anto007** [comment]
Ah, I see; thank you so much Lukas for making it clear to me that the data is loaded from external subdirectories; I kinda suspected this but didn't think it through properly. Many other bioinfo tools generate directly usable html output files and so, I was making the silly mistake of copying the Metaerg html output subdirectory alone to my laptop and then trying to view the files on my browsers. Once again I appreciate your patience with me; Closing this ticket now.

**Comment by kediza** [comment]
Hi, please assist. I have a similar problem, however my Java is enabled in all browsers
