### ISSUE TITLE
more than --cpus [N] used when calling metaerg.pl

### ISSUE THREAD

**Issue by chassenr** [xiaoli-dong/metaerg#22]
Hi,
I am running metaerg with the option ```--cpus 16```. However, when checking with htop, 60 cpus are being used (which is unfortunate since I only have 40 available). Do you know if this may be an issue with metaerg or with the system (and set-up) I am running it on?

Thanks!

Cheers,
Christiane

**Comment by Finesim97** [comment]
Hi,
This is normal metaerg behavior,  multiple annotation tools are started in parallel using the specified thread count. I would agree that this undesirable. It has lead to me getting scolded by the system admin multiple times. 🙈

Stay safe,
Lukas Jansen
