### ISSUE TITLE
Cannot download database from Calgary site

### ISSUE THREAD

**Issue by sipesk** [xiaoli-dong/metaerg#45]
<img width="654" alt="Screen Shot 2021-05-14 at 10 59 23" src="https://user-images.githubusercontent.com/25647467/118289531-72957b00-b4a3-11eb-9b6b-6c75ffdddd9b.png">

I cannot download the database. And when i try to run the docker to install I also get: 
<img width="1259" alt="Screen Shot 2021-05-14 at 11 00 26" src="https://user-images.githubusercontent.com/25647467/118289677-9789ee00-b4a3-11eb-84b6-c821649802cc.png">

Any help would be greatly appreciated

**Comment by MatteoSchiavinato** [comment]
Same here. I would like to know if there's an alternative link.

**Comment by sipesk** [comment]
Copying this link made it work ! :: https://github.com/xiaoli-dong/metaerg/issues/2
